### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by donovan-graham** [runspired/ember-gestures#4]
Hey runspired

I was wondering on the status of this repo. You've marked `ember-mobiletouch` as deprecated, but not much is happening here.  Please let me know, otherwise I need to make another plan.

D

**Comment by runspired** [comment]
This is usable (and in many many ways better than ember-mobiletouch) in it's current state.

I'm stalled on further development until I can get the next release of HammerJS out the door, and am working on an addon for an upgraded event-dispatcher to go with the RFC I've submitted.  This is unfortunately a project caught in the middle of those two projects due to it's dependence on both those eco-systems.

A patch release with a fixed hammer-time is coming today, and a 0.1.0 release using Hammer 2.0.5 is going to come out by the end of the day next Tuesday.

**Comment by donovan-graham** [comment]
Fantastic, thats great to hear.  

I have got some of the behaviour working by using the RecognizerMixin directly on a component. I wasnt sure how to setup the global behaviour. 

I also ran into a problem with click events being called after panEnd. Is there supposed to be some click-buster behaviour?

Thanks D

**Comment by runspired** [comment]
Restoring hammer time will provide fastclick, I deactivated it because the original implementation was buggy, the latest iteration I haven't hit any issues with yet.

**Comment by runspired** [comment]
Or you can use fastclick.js seamlessly with it in its current state

**Comment by sunil-shrestha** [comment]
I would like to try this ad-on at current state. Should i follow the guide from [ember-mobiletouch] (https://github.com/runspired/ember-mobiletouch#usage) for its usage? Or could you provide some examples how this can be used ?
